"""Generate an offline GitHub Actions gate for a vendored al2023-gate kit."""

from __future__ import annotations

import re
from pathlib import PurePosixPath

from . import util
from .artifacts import emit_report


def safe_path(value):
    path = PurePosixPath(value)
    if path.is_absolute() or ".." in path.parts or not re.fullmatch(r"[A-Za-z0-9_./-]+", value):
        raise ValueError("Workflow paths must be simple relative repository paths")
    return value


def render(state_path, kit_path="kits/al2023-gate", ami_catalog=None, region=""):
    state_path, kit_path = safe_path(state_path), safe_path(kit_path)
    catalog = " --ami-catalog '" + safe_path(ami_catalog) + "'" if ami_catalog else ""
    if region and not re.fullmatch(r"[a-z]{2}(?:-gov)?-[a-z]+-[0-9]+", region):
        raise ValueError("Workflow region must be an AWS region identifier")
    region_option = " --region '" + region + "'" if region else ""
    return f"""# Generated by al2023-gate ci-template. Runs offline; requires the kit at the configured repository path.
# State can contain secrets: use a sanitized inventory export or a protected runner-produced file, never upload raw state.
name: AL2023 migration gate
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  al2023:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      NO_COLOR: '1'
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install the vendored scanner
        run: python -m pip install './{kit_path}'
      - name: Check state evidence without AWS credentials
        run: al2023-gate terraform-state './{state_path}'{catalog}{region_option} --strict
"""


def run(args):
    text = render(args.state_path, args.kit_path, args.ami_catalog, args.region)
    if not util.is_dry_run(args):
        if not args.out:
            raise ValueError("--apply requires --out for the workflow file")
        from pathlib import Path

        target = Path(args.out)
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("x", encoding="utf-8") as handle:
            handle.write(text)
        emit_report({"written": True, "path": str(target)})
    else:
        print(text, end="")
    return 0
